version: '3'
services:
  postgres:
    image: postgres
    environment:
      POSTGRES_USER: myusername
      POSTGRES_PASSWORD: mysecretpassword
      POSTGRES_DB: databasetodo
    ports:
      - "5432:5432"
